version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: 04:00
    open-pull-requests-limit: 5
    reviewers:
      - mahori
    commit-message:
      prefix: ci
      include: scope

  - package-ecosystem: uv
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: 04:00
    open-pull-requests-limit: 10
    reviewers:
      - mahori
    commit-message:
      prefix: deps
      include: scope
